name: Other Runtime Package Test

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  deno-unit-test:
    name: Deno Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.29'
      - run: pnpm install
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-test:deno-unit-${{ inputs.package }}-${{ github.sha }}
      - name: Build dist cache
        if: steps.turbo-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-build-${{ github.sha }}
      - name: Build type cache
        if: steps.turbo-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-build:type-${{ github.sha }}
      - name: Deno cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ inputs.package }}-${{ hashFiles('**/pnpm-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-${{ inputs.package }}
      - name: Deno Unit Test
        run: pnpm test:deno-unit --cache-dir=".turbo" --filter=./packages/${{ inputs.package }}
  bun-unit-test:
    name: Bun Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.0.6'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-test:bun-unit-${{ inputs.package }}-${{ github.sha }}
      - name: Build dist cache
        if: steps.turbo-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-build-${{ github.sha }}
      - name: Build type cache
        if: steps.turbo-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-build:type-${{ github.sha }}
      - name: Bun Unit Test
        run: pnpm test:bun-unit --cache-dir=".turbo" --filter=./packages/${{ inputs.package }}
        timeout-minutes: 1
