name: Release

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/**
  release:
      types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package: ['gateway', 'rest', 'types', 'utils', 'bot', 'discordeno']
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@discordeno'
          cache: pnpm
      - run: pnpm install
      - name: build Package
        run: pnpm release-build --filter=./packages/${{ matrix.package }}
      - name: Bump Package Version
        if: ${{ github.event_name != 'release' && github.event.action != 'published' }}
        run: node ./scripts/bumpVersionByCommit.js ${{ matrix.package }}

      # If the action is running from a release use the latest tag, otherwise use the next tag
      - run: pnpm publish --tag ${{ github.event_name == 'release' && github.event.action == 'published' && 'latest' || 'next' }} --access public --provenance
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
